# Import for top level fastlane.tools configuration

platform :android do

  desc "Build apk for testing"
  lane :build do
    install
    UI.success "android build #gradle assembleRelease"
    #gradle(task: "clean assembleRelease", project_dir: ENV["PLATFORM_WORKDIR"])
    test
  end

  desc "Deploy a new build to the Play Store"
  lane :deploy do
    UI.success "android deploy #upload_to_play_store"
	UI.important "how to handle variants?"
    #app_info(file: ./build/any.apk)
    #upload_to_play_store(track: "internal")
  end

  desc "Release a new version to the Play Store"
  lane :release do
    UI.success "android release #upload_to_play_store"
    #upload_to_play_store(track_promote_to: "production")
  end

  desc "Install android build dependencies"
  private_lane :install do
    UI.success "android install #dependency ???"
  end

  desc "Test a newly built apk"
  private_lane :test do
    UI.success "android test #gradle test"
    #gradle(task: "test", project_dir: ENV["PLATFORM_WORKDIR"])
    #appetize
    #testfairy
  end

end
